export enum MutationTypes {
  SET_ITEMS = "SET_ITEMS",
  ADD_TASK = "ADD_TASK",
  COMPLETE_TASK = "COMPLETE_TASK",
  EDIT_TASK = "EDIT_TASK",
  DELETE_TASK = "DELETE_TASK",
  SET_LOADING = "SET_LOADING",
}
