export enum MutationTypes {
  SET_DAILY_ITEMS = "SET_DAILY_ITEMS",
  ADD_DAILY_ITEM = "ADD_DAILY_ITEM",
  SET_DAILY_ITEM = "SET_DAILY_TASK",
  DELETE_DAILY_TASK = "DELETE_DAILY_TASK",
  SET_DAILY_LOADING = "SET_DAILY_LOADING",
}
