export enum ActionTypes {
  FETCH_UPCOMING_TASKS = "FETCH_UPCOMING_TASKS",
  CREATE_UPCOMING_TASK = "CREATE_UPCOMING_TASK",
  EDIT_UPCOMING_TASK = "EDIT_UPCOMING_TASK",
  DELETE_UPCOMING_TASK = "DELETE_UPCOMING_TASK",
}
