export enum MutationTypes {
  SET_UPCOMING_ITEMS = "SET_UPCOMING_ITEMS",
  ADD_UPCOMING_TASK = "ADD_UPCOMING_TASK",
  SET_UPCOMING_ITEM = "SET_UPCOMING_TASK",
  DELETE_UPCOMING_TASK = "DELETE_UPCOMING_TASK",
  SET_UPCOMING_LOADING = "SET_UPCOMING_LOADING",
}
