export enum ActionTypes {
  FETCH_PROJECTS = 'FETCH_PROJECTS',
  FETCH_SINGLE_PROJECT = 'FETCH_SINGLE_PROJECT',
  CREATE_PROJECT = 'CREATE_PROJECT',
  UPDATE_PROJECT = 'UPDATE_PROJECT',
  DELETE_PROJECT = 'DELETE_PROJECT'
}
