export enum MutationTypes {
    SET_PROJECTS = "SET_PROJECTS",
    SET_LOADING = "SET_PROJECTS_LOADING",
    ADD_PROJECT = "ADD_PROJECT",
    UPDATE_PROJECT = "UPDATE_PROJECT",
    DELETE_PROJECT = "DELETE_PROJECT"
}
