export enum MutationTypes {
  SET_PROJECTS = 'SET_PROJECTS',
  SET_PROJECTS_LOADING = 'SET_PROJECTS_LOADING',
  ADD_PROJECT = 'ADD_PROJECT',
  UPDATE_PROJECT = 'UPDATE_PROJECT',
  DELETE_PROJECT = 'DELETE_PROJECT',
  CAST_PROJECT_TASKS = 'CAST_PROJECT_TASKS',
  DELETE_PROJECT_TASK = 'DELETE_PROJECT_TASK',
  EDIT_PROJECT_TASK = 'EDIT_PROJECT_TASK',
  CHANGE_PROJECT_TASK_STATUS = 'CHANGE_PROJECT_TASK_STATUS',
  // TODO: IMPLEMENT ADDING TASK TO PROJECT
  CRATE_PROJECT_TASK = 'CREATE_PROJECT_TASK'
}
