export enum ActionTypes {
    FETCH_TASKS = "FETCH_TASKS",
    FETCH_RECENT_TASKS = "FETCH_RECENT_TASKS",
    CREATE_TASK = "CREATE_TASK",
    EDIT_TASK = "EDIT_TASK",
    CHANGE_STATUS = "CHANGE_STATUS",
    DELETE_TASK = "DELETE_TASK"
}
