export enum MutationTypes {
    SET_PROJECT_TASKS = "SET_PROJECT_TASKS",
    SET_TODAY_TASKS = "SET_TODAY_TASKS",
    SET_RECENT_TASKS = "SET_RECENT_TASKS",
    ADD_ITEM = "ADD_ITEM",
    SET_ITEM = "SET_TASK",
    SET_LOADING = "SET_LOADING",
    CHANGE_STATUS = "CHANGE_STATUS",
    DELETE_TASK = "DELETE_TASK"
}
